server:
port: 8080

spring:
application:
name: api-gateway
cloud:
gateway:
globalcors:
corsConfigurations:
'[/**]':
allowedOrigins: "*"
allowedMethods: "*"
allowedHeaders: "*"
routes:
- id: user-service
uri: ${USER_SERVICE_URL:http://localhost:8081}
predicates:
- Path=/api/users/**

- id: movie-service
uri: ${MOVIE_SERVICE_URL:http://localhost:8082}
predicates:
- Path=/api/movies/**

- id: booking-service
uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
predicates:
- Path=/api/bookings/**