spring.application.name=booking-service
server.port=8083
spring.datasource.url=jdbc:h2:mem:bookingdb
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest